name: build

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - run: dotnet restore src/Birds.sln
      - run: dotnet build --no-restore src/Birds.sln -c Release
      - run: dotnet test test/Birds.Unit.Tests/Birds.Unit.Tests.csproj